#QP solver to be used in the NLP solver. String in  
QP_solver: 'PARTIAL_CONDENSING_HPIPM'
nlp_solver_type : 'SQP'
cython_solver: False #[BOOL]
obstacle:  False  #[BOOL]
Number_obstacles: 20 #[INT]
print_acados_status: True #[BOOL]
integrator_type: 'ERK'  #'ERK', 'IRK', 'GNSF', 'DISCRETE', 'LIFTED_IRK'
nlp_solver_max_iter: 15 #[INT]
cost_type: "LINEAR_LS"

# MPC parameters
Update_Frequency: 1 #¤[Hz]
Prediction_Frequency: 10 #[hz]
Prediction_Length: 10 #[s]

### Input constraints 
velocity_max: 0.5 #  [m/s]
velocity_min: -0.5 # [m/s]
angle_velocity_max: 10.  # [degrees/s]
angle_velocity_min: -10. # [degrees/s]

### Error constraints
ed_min: 0.0001 # [m]
ed_max: 0.0014 # [m]
eo_min: -2 # [rad]
eo_max: 2 # [rad]



# Slack variables
L2_Norm: 1.e+2 
L1_Norm: 1.e-1

# Weighting matrices
#Q_matrix:  [1.e-6,1.e-6, 0,0,0]
#Q_matrix_e:  [1.e-0,1.e-0, 0,0,0]
#Q_matrix_waypoint: [1.e-5,1.e-5, 0,0,0]
#Q_matrix:          [1.e-5, 1.e-5,0,0,0,]
#Q_matrix_e:        [1.e-8, 1.e-8,0,0,0,]
Q_matrix:          [0,0,0, 1.e-5,0]
Q_matrix_e:          [0,0,0, 0,0]
Q_matrix_waypoint: [0, 0]
R_matrix:  [1.e-9,1.e-9]